plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.6'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'

	// Validation API
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation("org.mapstruct:mapstruct:1.6.3")


	// Annotation processors — ORDER MATTERS: lombok → binding → mapstruct
	annotationProcessor 'org.projectlombok:lombok'

	// MapStruct processor
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'

    // Lombok-MapStruct binding (ORDER MATTERS)
	annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

	// lombok is needed at compile time for the main code, but not at runtime
	compileOnly 'org.projectlombok:lombok'

	// H2 and PostgreSQL drivers are needed at runtime, but not at compile time
	runtimeOnly 'org.postgresql:postgresql'



	// Test dependencies
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
	useJUnitPlatform()
}
