package com.example.EmpManagement.Mapper;

import com.example.EmpManagement.DTOs.EmployeeRequestDTO;
import com.example.EmpManagement.DTOs.EmployeeResponseDTO;
import com.example.EmpManagement.Model.Employee;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

@Mapper(componentModel = "spring") // telling mapstruct to make this spring bean...
public interface EmployeeMapper {

    // Map requestDTO ---> Entity
    @Mapping(target = "id", ignore = true) // we want to ignore the id field when mapping from requestDTO to entity because id is auto-generated by the database and should not be set manually.
    @Mapping(target = "department", ignore = true)
    @Mapping(target = "pfAccount", ignore = true)
    Employee toEntity(EmployeeRequestDTO employeeRequestDTO);

    // Map Entity ---> responseDTO
    EmployeeResponseDTO toResponseDTO(Employee employee);

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "department", ignore = true)
    @Mapping(target = "pfAccount", ignore = true)
    void updateEntityFromDto(EmployeeRequestDTO requestDTO, @MappingTarget Employee entity);

}
